# Generated by Django 4.0 on 2021-12-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_qq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qq',
        ),
    ]
